---
- name: Include common preflight tasks
  include_tasks: "common/preflight.yml"
  tags:
    - preflight

- name: Include common installation tasks
  include_tasks: "common/install.yml"
  tags:
    - install

- name: Include common configuration tasks
  include_tasks: "common/config.yml"
  tags:
    - config

- name: Include common launch tasks
  include_tasks: "common/launch.yml"
  tags:
    - launch
